### PR TITLE
Replaces jshint with eslint

### PR DESCRIPTION
**Pull request by jwerre**
Replaced jshint with eslint as discussed in #27

### CODE REVIEW

**Comment by jwerre** [comment]
I've add the following two lines to the lint config because I didn't want to mess with the code base too much. 

```json
      "no-control-regex": "off",
      "no-prototype-builtins": "off",
```

Ideally these are removed in the future.

**Comment by jankapunkt** [comment]
I will add the test and push it to this branch

**Comment by jankapunkt** [comment]
I actually found a faulty usage of the RegExp :scream: 

the regex groupings use `|` as separater but this should only be used in this way: `(\u0009|\u0020)` when used in this way `[\u0009|\u0020]` it actually accepts a `|` character. I am currently writing the tests in a way that we iterate all 1024 charcodes (generated) so we can make sure these regex are working correct.

Fortunately I took a look at. Maybe we should report this to the original project back?

**Comment by jankapunkt** [comment]
I updated the validator and it has now 100% coverage plus we test for all unicode charatcer ranges (valid and invalid ones) so there should be no false-positives or false-negatives sneak in anymore.

I wonder if this could be considered a security vulnerability? I mean it won't allow code injection (am I right?) but at least it would have allowed invalid characters and depending on where it's used could lead to issues.

**Comment by jwerre** [comment]
@HappyZombies @jankapunkt I think were good to merge here.

**Comment by jankapunkt** [comment]
From my end it's good I just wanted to @HappyZombies to take a look since I also worked on the code and hence am biased

**Comment by HappyZombies** [comment]
I am trying to run the linter but am getting the following error.

I am on Windows

Node -> v12.16.3

Error below.

```txt
PS D:\DJ\Projects\node-oauth2-server> npm run pretest

> @node-oauth/oauth2-server@4.0.0 pretest D:\DJ\Projects\node-oauth2-server
> eslint lib test index.js


Oops! Something went wrong! :(

ESLint: 8.0.0

Error: Cannot find module '@eslint/eslintrc/universal'
Require stack:
- node-oauth2-server\node_modules\eslint\lib\linter\linter.js
- node-oauth2-server\node_modules\eslint\lib\linter\index.js
- node-oauth2-server\node_modules\eslint\lib\cli-engine\cli-engine.js
- node-oauth2-server\node_modules\eslint\lib\eslint\eslint.js
- node-oauth2-server\node_modules\eslint\lib\eslint\index.js
- node-oauth2-server\node_modules\eslint\lib\cli.js
- node-oauth2-server\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (node-oauth2-server\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (node-oauth2-server\node_modules\eslint\lib\linter\linter.js:27:9)
    at Module._compile (node-oauth2-server\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
```

Is this a Node 12 issue maybe? I will try it again with Node 14

**Comment by HappyZombies** [comment]
I did do that, but I will try to delete the entire NPM cache, now I wonder if this a windows issue with version 8 lol.

**Comment by HappyZombies** [comment]
Yeah works within Docker...imma make an issue on the ESLint project. I tried searching but get unrelated jest stuff

**Comment by HappyZombies** [comment]
Yay version upgrade works! Went on v14.18.1

**Comment by oklas** [comment]
> I actually found a faulty usage of the RegExp 😱
> 
> the regex groupings use `|` as separater (logical or) but this should only be used in this way: `(\u0009|\u0020)` when used in this way `[\u0009|\u0020]` it actually accepts a `|` character. 
> 
> Maybe we should report this to the original project back?

Really good catch. Of course we should.

**Pull request merged**
