### PR TITLE
release 4.1.0 -> master

### PR DESCRIPTION
**Pull request by HappyZombies**
## Summary 📖 

This PR merges the changes from development into master.

### CODE REVIEW

**Comment by HappyZombies** [comment]
For this release, I'd like to just publish this manually -- once #49 is reviewed and further worked on. It can be our strategy moving forward.

**Comment by jankapunkt** [comment]
@HappyZombies yes I agree with manual publishing for this release, otherwise we would be stuck for a much longer time with outdated code.

Currently reviewing this one

**Review by jankapunkt — APPROVED** [review]
From what I've seen this is all the code I have already reviewed in the recent PRs without deviation. From my end this can be published.

**Comment by jankapunkt** [comment]
@jwerre can you please add your review so @HappyZombies can publish? I already approved.

**Comment by jwerre** [comment]
@jankapunkt yes, I'll check this out today. Sorry for the delay.

**Review by jwerre — APPROVED** [review]
Looks great!

**Comment by HappyZombies** [comment]
Published!

**Pull request merged**
