### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by jankapunkt**
## Summary

Release 5.0.0

## Added tests?

- [x] update tests in https://github.com/node-oauth/express-oauth-server,
       because the CI actually runs extra tests in this package on release-* branches

### CODE REVIEW

**Comment by jankapunkt** [comment]
The CI fails, because https://github.com/node-oauth/express-oauth-server tests fail (in[ tests for release](https://github.com/node-oauth/node-oauth2-server/actions/runs/5344674934/jobs/9689356644?pr=194)) so we need to update this repo, too.

**Comment by jankapunkt** [comment]
Released [v5.0.0-rc.1](https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.1)

**Review by jorenvandeweyer — APPROVED** [review]

**Comment by jankapunkt** [comment]
@jorenvandeweyer thanks for the review, I will wait a few more days to see if anyone reports issues with the RC. Maybe until end of next week or rather end of the month?

**Comment by jankapunkt** [comment]
This is blocked until #219 is properly covered

**Comment by jankapunkt** [comment]
FYI: I changed the target branch to `development` so we can safely work between `development` and `release-5.0.0`. We will then (once a stable 5.x release is published) rebase with master so master will become the latest stable, which is represented by `development` at that moment of release, while `development` will then continue to diverge from master with ongoing development, fixes etc.

**Review by jorenvandeweyer — APPROVED** [review]

**Review by jorenvandeweyer — APPROVED** [review]

**Comment by jankapunkt** [comment]
5.0.0-rc.3 released: https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.3

// cc @jorenvandeweyer @shrihari-prakash 

The rc.2 had 44 installations with no bigger issues reported during the last 14 days. If there are no bigger issues we should be good to merge and publish 5.0.0.

However: note, that we had to include some fixes (#228 #231) and some refactoring (#223 #225 #227) and updated tests (#224) which is why I think we should all thoroughly test with our setups and model implementations.

**Comment by jorenvandeweyer** [comment]
Nice! I think you can merge the branch into development. @jankapunkt 

Before releasing 5.0.0 we should consider if we want to make some more breaking changes because this would be the perfect (and only) opportunity.

**Comment by shrihari-prakash** [comment]
Sounds fantastic! Will test out rc3 in the coming week and let know if there's any issue :)

**Comment by jorenvandeweyer** [comment]
I upgraded some projects to `5.0.0-rc.3` :) At the moment everything seems to run fine.

**Comment by shrihari-prakash** [comment]
Hello @jankapunkt , what is the plan to go public with 5.x? Do you expect to release sometime in near future? From my side, I did not notice any issues in the past week.

**Comment by jankapunkt** [comment]
hi @shrihari-prakash you are right, we are currently testing with some staging setup. In the meantime there is still open, whether we want to fix https://github.com/node-oauth/node-oauth2-server/issues/104 because it's (slightly) breaking.

cc @jorenvandeweyer

**Comment by jorenvandeweyer** [comment]
We should first implement #104 imo.

**Comment by jankapunkt** [comment]
@jorenvandeweyer @shrihari-prakash I just recover from a cold and get back to this next week, preparing one more test with our staging env but looks all good so far

**Comment by jankapunkt** [comment]
Sure, I can do that, let me get the merging fixed and then I can create an RC.4 I think it's better to go the extra round but have later a stable final release

**Comment by jankapunkt** [comment]
@jorenvandeweyer @shrihari-prakash I will create the next (hopefully last) RC  and merge into `development` if you have nothing to report with this rc then I will release 5.0.0 and merge `development` into master, making 5.0.0 our new final latest stable.

**Comment by shrihari-prakash** [comment]
@jankapunkt @jorenvandeweyer , should we mention the breaking changing about scopes in the [Version 5 notes](https://github.com/node-oauth/node-oauth2-server/tree/release-5.0.0#version-5-notes) section of README?

**Comment by jorenvandeweyer** [comment]
@shrihari-prakash I mentioned it in the changelog.md file already

Before publishing v5.0.0 we should add some more details to it.

**Comment by jankapunkt** [comment]
Hmm tests seem to fail now, I will investigate

**Comment by jorenvandeweyer** [comment]
@jankapunkt are you already fixing it? if not, I can make some time free to fix it now.

**Comment by jankapunkt** [comment]
@jorenvandeweyer that would be awesome as I am on a conference right now

**Comment by shrihari-prakash** [comment]
@jankapunkt I hope you would be making a new RC for this push now.

**Comment by jankapunkt** [comment]
@shrihari-prakash yes I'm doing it today, currently occupied but I have some time for it later

**Comment by jankapunkt** [comment]
@shrihari-prakash @jorenvandeweyer RC4 is out: https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.4

**Comment by shrihari-prakash** [comment]
@jankapunkt , did something change related to `saveAuthorizationCode` function in model in this release? Had been getting a lot of type issues. Just want to check with you quick.

**Comment by jankapunkt** [comment]
@shrihari-prakash I think there were changes in the types file. Maybe something git overridden or is not up to date?

**Comment by shrihari-prakash** [comment]
I am checking the last commit.

**Comment by jorenvandeweyer** [comment]
I successfully migrated to rc-4. 

I only had to implement the breaking changes for scopes.

**Comment by shrihari-prakash** [comment]
Ok it was indeed a type issue with scope. My migration seems a little more complex. Will update once I am done migrating.

**Comment by jankapunkt** [comment]
@shrihari-prakash here is the diff: https://github.com/node-oauth/node-oauth2-server/compare/v5.0.0-rc.3...v5.0.0-rc.4#diff-7aa4473ede4abd9ec099e87fec67fd57afafaf39e05d493ab4533acc38547eb8

What actually breaks the types currently?

**Comment by shrihari-prakash** [comment]
@jankapunkt , @jorenvandeweyer , I just migrated to rc4 my framework which based is on this library and also made a sanity check on a production app that uses the framework. Nothing broke 👍🏻.

**Comment by jankapunkt** [comment]
@jorenvandeweyer @shrihari-prakash RC5 is out: https://github.com/node-oauth/node-oauth2-server/releases/tag/v5.0.0-rc.5

**Comment by jorenvandeweyer** [comment]
Nice! I propose we release v5 in the week of 6 november?

I'm seeing a lot of download on the rc.4 version.

**Comment by jankapunkt** [comment]
Yes! Let's fix the 6th as release date

**Comment by shrihari-prakash** [comment]
On my side, no issues in my production apps since rc5 upgrade so far. Things have been pretty good ever since rc4!

**Comment by jankapunkt** [comment]
@jorenvandeweyer @shrihari-prakash I generated documentation for 5.0.0 including a little migration guide here: https://node-oauthoauth2-server.readthedocs.io/en/release-5.0.0/index.html

Please review it and let me know if it's all good then I will publish 5.0.0 today.

**Comment by shrihari-prakash** [comment]
@jankapunkt on my side, I see only 2.x to 3.x migration. Is this normal? 
image

**Comment by shrihari-prakash** [comment]
Also, I don't know much about how read the docs works, but is the TOC supposed to show only the current section we are reading?
image
Isn't this difficult to navigate?

**Comment by jankapunkt** [comment]
So the link should be fixed. Regarding the navigation I found that read the docs changed their config model and the previous theme is not available anymore without adding tons of more config (requirements files, project.toml). I can look for a different theme but it should be builtin

**Comment by jankapunkt** [comment]
@shrihari-prakash the old theme is active now

**Comment by shrihari-prakash** [comment]
Looks perfect now! @jankapunkt

**Comment by jankapunkt** [comment]
@jorenvandeweyer @shrihari-prakash I finally published 5.0.0 :tada:

**Comment by shrihari-prakash** [comment]
@jankapunkt still don't see it yet?
image

**Comment by jankapunkt** [comment]
It's on NPM released, the GitHub release is waiting until I have merged it into master

**Pull request merged**
