### PR TITLE
Supported state in case of denial

### PR DESCRIPTION
**Pull request by FStefanni**
## Summary

This pr is related to issue #89, with point 13 and 20 (original pr https://github.com/oauthjs/node-oauth2-server/pull/576 and https://github.com/oauthjs/node-oauth2-server/pull/649 respectively).

It adds the missing state parameter.

## Linked issue(s)

The reference issue is the #89.

## Added tests?

Yes, and updated already existent tests.

## OAuth2 standard

RFC6749, section 4.1.2.1

### CODE REVIEW

**Comment by jankapunkt** [comment]
please set target to development not master

**Comment by FStefanni** [comment]
Hi,

done

Regards

**Review by jankapunkt — APPROVED** [review]

**Comment by jankapunkt** [comment]
@HappyZombies @jwerre can you please second-check and merge, if approved?

**Review by jwerre — APPROVED** [review]

**Comment by ronaldsteen** [comment]
@jankapunkt are you planning a release including this fix anytime soon? Our projects depend on this fix, and I'd like to return to a public version 👍

**Comment by jankapunkt** [comment]
Hey @ronaldsteen I currently prepare to finish our automated release workflow, see #117 once this is merged (one workflow is not tested yet, which is the one running for a new release) then I want to create `4.2.0` as new release with all recent fixes and features included, unfortunately it won't happen this week anymore, I really need the weekend as I worked over the new year right now

**Pull request merged**
