### PR TITLE
DRAFT: Release workflows

### PR DESCRIPTION
**Pull request by jankapunkt**
This PR implements a multi-stage testing and release workflow, as proposed on #36 

The proposed workflow logic is therefore the following:

A. PR to development and master + pushing to them:
  - run basic unit tests (tests.yml)
  - do not run this basic tests on `release-*` branches, since they have their own extended workflow

B. PR / Push to a `release-*` branch:
  - run npm audit
  - run basic unit tests
  - run extended integration tests against all adapter packages
  - run publish dry-run for npm registry
  - run publish dry-run for github packages registry

C. Create a (new release)[https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository]
 - execute B
 - finally publish to NPM
 - finally publish to GH

The workflows A and B are triggered fully automated, while C still needs a release to be created by one of the maintainers. This is because a pull request to a `release-*` does not necessarily mean to create a new release from the package.

On the other hand - this could also be changed to, say, automatically create a new release at the end of workflow B when all checks have passed

### CODE REVIEW

**Comment by jankapunkt** [comment]
@HappyZombies in it's current state it would mean to create a GitHub release (which also includes a Tag, yes)

Merging into master should be always the latest **stable** release, which is what many other projects do as well.

**Comment by jankapunkt** [comment]
@HappyZombies @jwerre I changed the base branch to `release-tests` the idea is the following:

we can't test the new actions just by opening a PR (because if that would be possible, someone could just open a PR, start any actions on the CI and maybe steal credentials or anything else). 

In turn we need to pull this into the `release-test` branch and once pulled (after review) we can test the new included `test-release-yml` action, which also includes a npm publish and github publish dry run.

Once this is working we can pull it into `development` and have our release system ready for any new release :-)

**Comment by jankapunkt** [comment]
@jwerre @HappyZombies just a short ping - can you please read the above comments and let me know if you understand the intended steps? If you confirm, I'll merge into `release-tests` and immediately create a PR into `development` with additional release-check tests (but without an actual release, as this will be done manually using a GH release)

**Review by jwerre — APPROVED** [review]
Wonderful!

**Comment by jankapunkt** [comment]
I will merge this after 4.1.0 has been released

**Pull request merged**
