### PR TITLE
Merge dev into master

### PR DESCRIPTION
**Pull request by jankapunkt**
We forgot to merge dev into master but master should reflect the latest stable (which is current dev)

### CODE REVIEW

**Review by HappyZombies — APPROVED** [review]
Code Review Completed

**Review by jorenvandeweyer — APPROVED** [review]
Looks good. Maybe we should include node v20 in the test-release.yaml

**Comment by jankapunkt** [comment]
Updated the CI to Node 20. I also used the PR to update links in the README and added this repo finally to readthedocs so we can host an up-to-date documentation.

However, for the actual documentation Update I will create another PR (there are still old links to OAuthJs etc. in the docs).

**Comment by jankapunkt** [comment]
@HappyZombies @jorenvandeweyer can you please review again so I can merge?

**Review by jorenvandeweyer — APPROVED** [review]

**Pull request merged**
