### PR TITLE
Removed Bluebird and Promisify-Any

### PR DESCRIPTION
**Pull request by jwerre**
## Summary

Removed support for callbacks and removed `bluebird` and `promisify-any` dependencies. I'm not sure how you want to merge this since this is a major version update (v5).

## Linked issue(s)

- #19
- #20

## Added tests?

No tests added but many are refactored and changed.

### CODE REVIEW

**Comment by jwerre** [comment]
@jankapunkt CodeQL is picking up a hardcoded password in the test suite. Is there a way to ignore tests? What is the best solution for this?

**Comment by jorenvandeweyer** [comment]
You can mark it as "used in test". Or make a variable for the authorization header.

**Comment by jankapunkt** [comment]
I always use `Math.random().to string(16)` to generate a simple random hex password if the password itself is not to be tested.

**Comment by jankapunkt** [comment]
@jwerre this is a great step towards modern JS but I'd like to delay it until we merged the open PRs that fix code and/or compliance issues otherwise we will have to resolve lots of merge conflicts what do you think?

**Comment by jwerre** [comment]
@jankapunkt Yes, I was watching all the PRs coming in and thinking the same thing. No rush on this.

**Comment by Uzlopak** [comment]
If we merge #109 then this whole branch will be unmergeable.

**Comment by jankapunkt** [comment]
@Uzlopak partially yes but it already needs refactoring/merging work so I think we should just set a cut after the recent 5 or 6 open PRs and exclusively focus on this one all together then it will be fixed fast and we can continue

**Comment by esatterwhite** [comment]
@jankapunkt Is this still valid? can it be merged?

**Comment by jankapunkt** [comment]
@esatterwhite this is still to be done, however there are a few things blocking:

- first we want to merge #70 
- #70 itself needs to be fixed, since after a merge conflict resolve the tests now fail :sob: 
- this needs to resolve merge conflicts but I wouldn't do before #70 is merged, otherwise we will have to do it again afterwards
- it may require to fix things after the merge conflict resolve, as in #70 

I'm currently allocating more time but support from the community is also highly appreciated. Please watch the progress in #70, once merged we will definitely continue here.

**Comment by jankapunkt** [comment]
Hey @jwerre I struggled hard to merge this and by the time I realized that the merge lost some code from `development`, the two branches are too far away from each other, also, because #109 changed many ES5 classes to ES6 classes and the diff was unbearable to comprehend...

I used your impl. as blueprint for creating #190 which I started from scratch, based on the latest `development` state.

I will close this as superseded by #190 please don't feel bad about it, the merge was too risky to loose recent fixes.

**Pull request closed without merging**
