### PR TITLE
refactor(types): update types to be more concise

### PR DESCRIPTION
**Pull request by dhensby**
1. Don't use `| undefined` for props that are already declared optional (`undefined` is an implied value)
2. prefer using the [`Record`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) built-in type over object maps

### CODE REVIEW

**Review by jorenvandeweyer — APPROVED** [review]
FYI: optional is not the same as undefined, by removing this, passing an undefined value is not allowed anymore.

**Comment by dhensby** [comment]
> FYI: optional is not the same as undefined, by removing this, passing an undefined value is not allowed anymore.

I'm almost certain that's not right: https://www.typescriptlang.org/play/?#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDKHIAOUA9sdGAJ4D8AXMllKAOYDceAvnngmSCzJIWRuiEBeXCXKUoNRgFcQAEwgxQEFci6cgA

This doesn't give a syntax error

**Comment by dhensby** [comment]
It was off the back of [this](https://github.com/node-oauth/node-oauth2-server/pull/309#issuecomment-2248244816) comment that I made the type just `string[]`.

Basically the types reflect the ideal typings and not an enumeration of every single type that could be accepted. By limiting the type this way, we also make the upgrade path for those following the types easier if/when we remove the `string` support. It's also not a breaking change as it's the current typing, so we aren't introducing any new issues by leaving the typing like this.

**Review by jankapunkt — APPROVED** [review]

**Comment by jankapunkt** [comment]
From my end it's ok but I'm only using a few of them for my IDE intellisense.

**Review by jorenvandeweyer — APPROVED** [review]

**Pull request merged**
