### PR TITLE
Contribution guidelines

### PR DESCRIPTION
**Pull request by jankapunkt**
This is just a draft for now as things are not 100% clear. Related discussion: #5

### CODE REVIEW

**Comment by HappyZombies** [comment]
README is good, overall just had some minor questions

**Comment by HappyZombies** [comment]
Also another thing, should we discuss about deleting branches after a PR?

**Comment by jankapunkt** [comment]
Good question, I never delete branches but that's something I learned back at my previous company. I could do some research on the pros and cons

**Comment by HappyZombies** [comment]
@jankapunkt some small typos, once those are address I will approve and merge!

**Pull request merged**
