### PR TITLE
Fixed issue 89, point 32, original issue 716

### PR DESCRIPTION
**Pull request by FStefanni**
Hi,

this is just a very minimal pr to fix the point number 32 of issue #89, matching the pr 716 in the original project.

Regards

### CODE REVIEW

**Comment by jorenvandeweyer** [comment]
`npm install` is previously always done with node version < 16.

**Comment by FStefanni** [comment]
Hi,

ok: tell me the preferred npm version and node version, and I'll fix this.

Regards

**Comment by FStefanni** [comment]
Hi,

rebased using:
* node v14.18.1
* npm 6.14.15

Regards.

**Comment by HappyZombies** [comment]
These changes are covered by dependabot so there's no need to open a new PR for these module updates

**Pull request closed without merging**
