### PR TITLE
Use native promises and async/await, drop bluebird and promisify-any

### LINKED ISSUE #19: Remove Bluebird dependency
We should be able to remove Bluebird as a dependency in favor of standard ES6 Promises.

### LINKED ISSUE #20: Remove promisify-any dependency
Just use [`util.promisify`](https://nodejs.org/docs/latest-v14.x/api/util.html#util_util_promisify_original)

### LINKED ISSUE #48: Remove support for callbacks in models
Callback support adds unneeded complexity. Models should be exclusively promise based version ^4.1.0. https://github.com/node-oauth/node-oauth2-server/issues/20#issuecomment-943633108

### LINKED ISSUE #57: Get rid of dependencies?
I just checked a bit the current dependencies we have.

Regarding bluebird and promise I think we are good to remove them and they are covered by these issues already: #19 #20 #48 

The other dependencies are the following:

### type-is

npm: https://www.npmjs.com/package/type-is
github: https://github.com/jshttp/type-is

#### dependencies:
- media-typer: https://www.npmjs.com/package/media-typer
- mime-types: https://www.npmjs.com/package/mime-types

#### usage:

This project uses `type-is` to parse and classify request types (like `text/html; charset=utf-8` or `application/json`).

See in code: https://github.com/node-oauth/node-oauth2-server/blob/development/lib/request.js#L8

#### analysis:

While `mime-types` is updated regularly, the `type-is` and `media-typer` have not been released in a few years but are at the same time downloaded in the ten-millions. This can mean they are quite mature but it could also mean that the owners may have not much time anymore to maintain.

The may also have no 2FA setup yet (because a few years ago nobody cared so much but a few people who were security-aware).
We should ask the owners (directly via Email) if they have setup 2FA in order to prevent supply chain attacks on their repos, since their combination (yeaqrs ago released + 20 million downloads) would be targets for SCA in my view.

#### remove or not

I am not sure if removing makes things easier. Parsing is often a complicated thing and request types are variying a lot. Would need more analysis, if we need only a few types exclusively.

## basic-auth

npm: https://www.npmjs.com/package/basic-auth
github: https://github.com/jshttp/basic-auth

#### dependencies:

- safe-buffer: https://www.npmjs.com/package/safe-buffer

#### usage:

This project uses `basic-auth` in order to retrieve and parse the `auth` header of a request.

See in code:
- https://github.com/node-oauth/node-oauth2-server/blob/development/lib/handlers/token-handler.js#L20
- https://github.com/node-oauth/node-oauth2-server/blob/development/lib/handlers/token-handler.js#L175

#### analysis

Both packages are not published in 2 years. Their usage is also in the millions. While I can't say about the activity for the owner of `basic-auth` I know at least for the author of `safe-buffer` that he is actively maintaing his repos. The same thing applies regarding 2FA, we should ask the owners (directly via Email).

> Removing basic-auth would be a major version change since it throws errors. These errors may be being caught in peoples apis.

#### remove or not

This is a more interesting issue, since parsing the auth header is way simpler than parsing thousands of combinations of requests. We also could get rid of both deps, since the node-native buffer should be sufficient.

###

### PR DESCRIPTION
**Pull request by jankapunkt**
## Summary

**This is a breaking change!**

- Removes all bluebird and promisify-any dependencies.
- Uses `async/await` in favour of `Promise` where applicable
- Removes callback support
- updated tests
- improved readability and structure
- replace `Promise.` calls in async functions with native behaviour
  - use `await` chain instead of `Promise.all`
  - throw error instead of `Promise.reject`
  - return values instead of `Promise.resolve`
  - some tests still use `Promise.resolve` in combination with sinon stubs but that's because in this case the pattern is more concise than an `async` function counterpart

**Relation to the prior PR**

There was a prior PR that did basically the same as this one: https://github.com/node-oauth/node-oauth2-server/pull/107

The `development` branch became too different from #107 and the merge diff was unbearable to read. I closed #107 and used it as blueprint to implement it from the latest `development` state.

**Release proposal**

If this gets accepted and merged we should create a `5.0.0-rc.0` release to allow early adopters to integrate and report any issues beyond the expected ones. Please comment.

## Linked issue(s)

#19 
#20 
#15 
#48 

## Involved parts of the project

- grant types
- handlers
- utils
- OAuth2Server class
- tests

## Added tests?

- tests updated

## OAuth2 standard

- no changes regarding standard

## Reproduction

- clone, run tests
- create local package and integrate with own project

### CODE REVIEW

**Review by jorenvandeweyer — APPROVED** [review]
I'm in favour of removing callback support and releasing a `5.0.0-rc.0`.

This makes the transition to typescript a lot easier!


I do see something inconsistent in the PR.

Sometimes the `Promise.all` is replaced by a chain of awaits and sometimes it's not. Maybe we can remove all `Promise.all` functions?

**Comment by jankapunkt** [comment]
@jorenvandeweyer thanks a lot for your opinion on this and the hint to the `Promise.all`.

Regarding the callbacks - I tend towards this approach, too!

Regarding Promise.all - I will remove them entirely. I also think there were issues with Promise race conditions by using Promise.all (mentioned deep in the conversations of one of the issues....). Replacing this with chains of awaits woulf automatically prevent unintended execution order.

**Comment by jankapunkt** [comment]
@HappyZombies @Uzlopak @jorenvandeweyer some update on this. I manually wrote a few emails to repo owners that I found in our dependants list. I asked them about their perspective on this and the vast majority is fine with going full async and dropping callbacks in 5.x. I will therefore continue the proposed strategy and release the `5.0.0-rc.0` this week

**Comment by HappyZombies** [comment]
@jankapunkt thanks for reaching out to devs about this. Although  I think it might be possible to support both promise and a callback (I have seen this before in other modules I've used), it's obviously just more effort. If we're good with removing callback support entirely, then let's do it 👍

**Pull request merged**
